AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dakobed-serverless-pipeline

  Sample SAM Template for dakobed-serverless-pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  KinesisProcesserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: handler/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        KinesisHandler:
          Type: Kinesis # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            BatchSize: 100
            Stream: arn:aws:kinesis:us-west-2:710339184759:stream/DakobedStream
            StartingPosition: TRIM_HORIZON
#            StartingPostion: LATEST


#
Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt KinesisProcesserFunction.Arn
  KinesisProcesserFunctionRolee:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt KinesisProcesserFunctionRole.Arn
